### PR TITLE
feat: reusable-form-component

### PR DESCRIPTION
**Pull request by austinpendleton**
## Describe your changes
Started creating reusable form component. I have ran in to a roadblock with styling the component in Storybook.
## Issue ticket number and link
[](https://apiary-edtonomy.atlassian.net/jira/software/projects/SLOP/boards/2?selectedIssue=SLOP-4)
## Checklist before requesting a review

- [x] I have performed a self-review of my code
- [x] If there are changes to components, I have added / updated automated tests
- [ ] I have made any necessary updates to Storybook to accompany these changes
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by austinpendleton** [comment]
Hello team!

I believe I have most of the reusable form component close to being completed but I am having some issues with styling via storybook. I would really appreciate some help on this! 

Thank you for taking a look!

**Comment by colburncodes** [comment]
@austinpendleton  I pulled your branch and test your feature. I believe cx is a library that needs to be imported.  I didn't make use of it for the simple fact the goal was to get the component to show in storybook. Not sure why what you had initially implemented did not work it looked good.

```
import { Form } from "./index";

export default {
  title: "Components/Form",
  component: Form,
};

// Define your stories
export const Default = () => (
  <Form>
    <Form.TextInput
      className={"border rounded p-2 mb-4 focus:outline-none focus:border-blue-500"}
      id="username"
    />

<Form.TextArea className={"border rounded p-2 focus:outline-none focus:border-blue-500"} id="comment" labelText="Comment" />
  </Form>
);
```

So, I just did this to actually see it display in storybook. But yea looks like all is left is cx and mess around with the css a bit. 

Screen Shot 2023-09-19 at 6 30 32 PM

**Review by colburncodes — CHANGES_REQUESTED** [review]
@austinpendleton  I pulled your branch and test your feature. I believe cx is a library that needs to be imported.  I didn't make use of it for the simple fact the goal was to get the component to show in storybook.

```
import { Form } from "./index";

export default {
  title: "Components/Form",
  component: Form,
};

// Define your stories
export const Default = () => (
  <Form>
    <Form.TextInput
      className={"border rounded p-2 mb-4 focus:outline-none focus:border-blue-500"}
      id="username"
    />

<Form.TextArea className={"border rounded p-2 focus:outline-none focus:border-blue-500"} id="comment" labelText="Comment" />
  </Form>
);
```

So, I just did this to actually see it display in storybook. But yea looks like all is left is cx and mess around with the css a bit. 

```
Required namespaced components:
Text input
Textarea
Number
Dropdown (select)
```

Looks like Number and Dropdown need to be implemented. [Form Component](https://apiary-edtonomy.atlassian.net/jira/software/projects/SLOP/boards/2?selectedIssue=SLOP-4)


Screen Shot 2023-09-19 at 6 30 32 PM

**Comment by skwisgaarr8-9** [comment]
@austinpendleton The submit button does not show on storybook and that is because when you use the `Button` component you need to pass in a `className` prop to style it. It could look like this
```
Form.Submit = ({ children, className }) => {
  return (
    <Button className={className} type="submit">
      {children}
    </Button>
  );
};
```

or perhaps if `Form.Submit` will always be styled the same way, you could just style the `Button` there and then you do not need to pass `className` as a prop

**Review by skwisgaarr8-9 — CHANGES_REQUESTED** [review]
@austinpendleton The submit button does not show on storybook and that is because when you use the `Button` component you need to pass in a `className` prop to style it. It could look like this
```
Form.Submit = ({ children, className }) => {
  return (
    <Button className={className} type="submit">
      {children}
    </Button>
  );
};
```

or perhaps if `Form.Submit` will always be styled the same way, you could just style the `Button` there and then you do not need to pass `className` as a prop. 

In addition to that, the `Button` component takes in a `title` prop that is used as the text of the button so you don't need to use `{children}`. 

```
Form.Submit = ({ title, className }) => {
  return (
    <Button title={title} className={className} type="submit"/>
  );
};
```

**Comment by austinpendleton** [comment]
button styled



---Sorry for the delay on the changes to the button, but I have now styled it. Here is a screenshot of what we are looking at now and I have pushed the updated code!

**Review by jahorwitz — CHANGES_REQUESTED** [review]
@austinpendleton This looks great so far, but I have a minor addition to make;

Could you please take a look at this example to see how to integrate `react-hook-form` into this component? Each of these namespaced components needs to accept props for registering the field with `react-hook-form`, and the storybook entry should give an example of using the `useForm` hook for managing form state

**Comment by austinpendleton** [comment]
I have integrated `react-hook-form` in to the form.stories.jsx including a `register` and `handleSubmit` prop.

These changes can be seen on the most recent push!

**Review by skwisgaarr8-9 — APPROVED** [review]

**Review by skwisgaarr8-9 — CHANGES_REQUESTED** [review]
The form looks really good. I just noticed a few minor styling points we could fix. 

**Button**:
- the button width needs adjusting
- remove the height
- the font family, style, and size should be set

I set the class name for the button to: 

`className="font-bold font-arial bg-yellow-400 text-lg/4 text-black w-full border py-4 px-4"`

and it looked good to me. 

**Inputs**:
- inputs should have 1-px borders
\*I couldn't see anywhere on the Figma that showed 2-px borders but I could be wrong!

**Labels**:
- set font size to 18-px with `text-lg`

**Comment by austinpendleton** [comment]
I appreciate the review @skwisgaarr8-9! I have updated these styles and committed the updated code!

**Review by skwisgaarr8-9 — APPROVED** [review]

**Review by jahorwitz — APPROVED** [review]

**Pull request merged**
