### PR TITLE
Feature/slop 4/slop fest edit modal

### PR DESCRIPTION
**Pull request by SamPage4427**
## Describe your changes
Utilized the Slop Fest Modal to give the user the ability to change their created slop fest after creation.
#### Changed:
- Location of the fest mutations to a folder inside the mutations folder
- Slop Fest Modal to include the logic for updating a fest through GraphQL
- Changed the edit fest link to a button to handle the opening of the modal
- Changed Slop Fest Modal to prepopulate form values depending on the location of the modal
## Issue ticket number and link
[Slop 4](https://tripleten-apiary.atlassian.net/browse/SLOP-4?atlOrigin=eyJpIjoiNzg0NjlhNDY3ZWNhNGM2NGE4NTk5NzcxMzBkNWQwOTMiLCJwIjoiaiJ9)
## Checklist before requesting a review

- [x] I have performed a self-review of my code
- [x] If there are changes to components, I have added / updated automated tests
- [ ] I have made any necessary updates to Storybook to accompany these changes
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by AidanWard19** [comment]
I'm not sure if this pertains to your ticket, but when I try to edit dates & guest and change the name of the fest, I get this error: 
Capture
Other than that, it looks great and I don't see anything wrong.

**Comment by SamPage4427** [comment]
> I'm not 100% sure if this pertains to your ticket, but when I try to edit dates & guest and change the name of the fest, I get this error: Capture Other than that, it looks great and I don't see anything wrong.

I'm not able to recreate that error. Originally I was getting that error from the attendees array but I thought I fixed that since I'm no longer getting that error

**Comment by AidanWard19** [comment]
Are there any backend updates that I'm missing? Other than that, I'll try to figure out what I could be doing wrong. If someone else peer reviews this, it would be helpful if they could also test for this error.

**Comment by SamPage4427** [comment]
> Are there any backend updates that I'm missing? Other than that, I'll try to figure out what I could be doing wrong. If someone else peer reviews this, it would be helpful if they could also test for this error.

Not that I'm aware of. 
image
Is this included in the code? This is where I handled that error I thought

**Comment by mnunezsa95** [comment]
> > Are there any backend updates that I'm missing? Other than that, I'll try to figure out what I could be doing wrong. If someone else peer reviews this, it would be helpful if they could also test for this error.
> 
> Not that I'm aware of. image Is this included in the code? This is where I handled that error I thought

I am not getting this error either. This seems fine

**Comment by mnunezsa95** [comment]
@SamPage4427 This looks great, the only thing I would add is preventing the default behavior of the edit modal. When you click the "save edits" button, I noticed that it submits and refreshes the page. I would just prevent this behavior to allow for a friendly-er experience

**Review by jahorwitz — APPROVED** [review]

**Pull request merged**
