### PR TITLE
feat/slop-37/fest attendees

### PR DESCRIPTION
**Pull request by skovakina**
## Describe your changes
Implemented a feature on the Slop Fest page to visually differentiate between attendees and invitees. Attendees who have RSVP'ed 'attending' are now displayed with a yellow pill, while invitees who haven't RSVP'ed appear with a gray pill. 
image

## Issue ticket number and link
[slop-37](https://tripleten-apiary.atlassian.net/jira/software/projects/SLOP/boards/2?selectedIssue=SLOP-37)

## Checklist before requesting a review

- [x] I have performed a self-review of my code
- [ ] If there are changes to components, I have added / updated automated tests
- [ ] I have made any necessary updates to Storybook to accompany these changes
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

### CODE REVIEW

**Review by fdlai — CHANGES_REQUESTED** [review]
Hi! I'm seeing a couple of issues:

1) In the 1st screenshot, if a user has RSVP'd, it shows their name duplicated.


2) In this 2nd screenshot, it looks like in this section the user is not highlighted yellow.


For the duplication part, I think that's happening because when a user RSVP's, they become an attendee but are not removed from being an invitee. My 1st thought is to make some logic so that if a user is only an invitee, it displays the grey box. But if a user is both an attendee and an invitee, it only displays the yellow box. Just a thought. I'm sure there's multiple ways to do it.

**Comment by skovakina** [comment]
In this update, attendees are also shown on the fests page. I also fixed some CSS for keywords, titles, and dates.

**Review by fdlai — APPROVED** [review]
Hi! I think this branch is good, but it has problems if I run this branch on it's own. I show in the video. I think we need to test this branch with this other one, because they sort of depend on each other: https://github.com/jahorwitz/slopopedia/pull/82

I show in the video, I do a temporary merge of the two branches in order to test this one. Everything works great then! Good work!

https://www.loom.com/share/74dbcf469c014ebbaf29c24ed279d338

**Review by marzahlde09 — APPROVED** [review]
This worked following Fred's guidance to merge!

**Review by tomershvueli — CHANGES_REQUESTED** [review]
In this branch, I'm seeing a regression where I'm not able to see a Fest that the current user created. 

This is the Fest page on the `main` branch (note the 'tomer fest 3'):
Screenshot 2024-06-02 at 09 07 23
This screenshot is from this branch, where I'm not seeing that fest listed: 
Screenshot 2024-06-02 at 09 07 57

**Comment by skovakina** [comment]
fixed fest id, so users should be able to see fest correctly

**Review by tomershvueli — APPROVED** [review]
LGTM!

**Pull request merged**
