### PR TITLE
feature/slop-79/Protect routes that require a specific user(s)

### PR DESCRIPTION
**Pull request by fdlai**
## Describe your changes
Protect 3 routes: "/articles/:id/edit" , "/fests/:festId" , "/fests/:festId/discussion". 
The route "/articles/:id/edit", should only be viewable by the article author.
The routes "/fests/:festId" and "/fests/:festId/discussion", should only be viewable by the fest creator (who is naturally an invitee to their own fest) and any other invitees/attendees. 

**Testing:**
In order to test this, I recommend copying the url on one of these routes, when logged in as an authorized user. And then logging in to a user that shouldn't have access, and pasting the url into the browser. If unauthorized, you should be redirected to the home page.

**Note** that if you create a fest in the Keystone UI, the user that you make the creator of the fest, is not automatically made an invitee or attendee. Therefore, if you decide to create a fest in the Keystone UI, please also add the creator of the fest as an invitee. If you create the fest within the actual application, then the creator is automatically added an invitee of their own fest.

## Issue ticket number and link
slop-79
https://tripleten-apiary.atlassian.net/jira/software/projects/SLOP/boards/2?selectedIssue=SLOP-79

## Checklist before requesting a review

- [x] I have performed a self-review of my code
- [ ] If there are changes to components, I have added / updated automated tests
- [ ] I have made any necessary updates to Storybook to accompany these changes
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

### CODE REVIEW

**Review by bduckdev — COMMENTED** [review]
Hi Fred, I just tested some of your code and wanted to know if there is an issue with my testing methodology or if this is an issue that needs to be fixed with the code itself.

I created an account and created a fest related to the user. I then attempted to access the `fests/:festId` and `fests/:festId/discussion` routes as the signed in use and was unable to view the routes. The issue is displayed in the video below:

https://github.com/jahorwitz/slopopedia/assets/108188726/e354b710-deb1-46b4-9619-50b5a377ee43

**Comment by fdlai** [comment]
> Hi Fred, I just tested some of your code and wanted to know if there is an issue with my testing methodology or if this is an issue that needs to be fixed with the code itself.
> 
> I created an account and created a fest related to the user. I then attempted to access the `fests/:festId` and `fests/:festId/discussion` routes as the signed in use and was unable to view the routes. The issue is displayed in the video below:
> 
>  2024-05-29.18-53-31.mp4

@bduckdev Hi! So, I think the issue is that only invitees and attendees are allowed access to those routes. But you've created a fest from within the keystone ui, which doesn't automatically place the creator as an invitee or attendee. If you create a fest in the actual application, the creator is automatically given the invitee status. So, within the keystone ui, you can just add the creator as an invitee or attendee, and then I believe it should work. Or, you can create a fest in the actual browser, and it will do that automatically.

**Review by bduckdev — APPROVED** [review]
Thanks for the clarification Fred, it works now!

**Review by tomershvueli — APPROVED** [review]
Nice reusable solution! LGTM!

**Pull request merged**
