### PR TITLE
Feature / Slop 80 / Protect delete draft blog with modal

### PR DESCRIPTION
**Pull request by ATribbey**
## Describe your changes
Protected draft deletion with the pre-existing delete confirmation modal.

## Issue ticket number and link
https://tripleten-apiary.atlassian.net/browse/SLOP-80?atlOrigin=eyJpIjoiNmY1MDYzNWZkZjM1NDliZTkyZjI0ZWNiMjE4MDY5YjgiLCJwIjoiaiJ9

## Checklist before requesting a review

- [x] I have performed a self-review of my code
- [ ] If there are changes to components, I have added / updated automated tests
- [ ] I have made any necessary updates to Storybook to accompany these changes
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

### CODE REVIEW

**Review by skovakina — CHANGES_REQUESTED** [review]
Hello! When I try to delete a draft blog post, I get errors.
image

**Review by fdlai — COMMENTED** [review]
If you merge main into this branch, that fixes the issue of not being able to actually delete it. Seems to work great then! The only improvement I would suggest, is also using the delete-confirmation modal for the button I show in the screenshot below as well.

**Review by fdlai — APPROVED** [review]
Everything seems to work perfectly! Great job!

**Review by marzahlde09 — APPROVED** [review]
Seems to work! No console errors.

Just need to resolve merge conflicts!

**Review by tomershvueli — APPROVED** [review]
💯

**Review by skovakina — APPROVED** [review]
works great now!

**Pull request merged**
