### PR TITLE
Feature/slop 24/main page movie list

### PR DESCRIPTION
**Pull request by fostert14**
## Describe your changes

- Previously the size of movies was being passed as an object to the MovieCard. I adjusted the colSizes constant to have a size value associated with them, then carried that over to the parent div in MovieCard.
- Adjusted the max height of images to be 80vh.

## Issue ticket number and link

[Slop-24/Improvement: Main Page Movie List](https://tripleten-apiary.atlassian.net/browse/SLOP-24?atlOrigin=eyJpIjoiMmY2MGM5NTU2NWI4NDYxZGFiYzBlOGZjNzg2YWVmNmEiLCJwIjoiaiJ9)

## Checklist before requesting a review

- [x] I have performed a self-review of my code
- [ ] If there are changes to components, I have added / updated automated tests
- [ ] I have made any necessary updates to Storybook to accompany these changes
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by mnunezsa95** [comment]
I think it looks good overall, but here's an issue I see. Not sure if it is out the scope of your ticket. Sam or Francis might be able to speak more on it. Right now, when a movie has alot of keywords, it starts to look very messy. Not sure if this is by design or accidental, but there's a way where you could make it so that only limit it to 3 or 5 keywords show up (again not sure if this is something in your scope or something that should even be done). 



Screenshot 2024-03-20 at 11 27 31 AM
Screenshot 2024-03-20 at 11 28 08 AM

**Comment by mnunezsa95** [comment]
Additionally, I know this is NOT on your ticket, but could be worth editing since it's simple and easy. but the recently added on the fron page needs some padding. You could probably just add it on this ticket, so that we don't need another ticket for it.

Here is the front page now
Screenshot 2024-03-20 at 11 35 26 AM

Here is what Figma has
Screenshot 2024-03-20 at 11 36 36 AM

**Comment by mnunezsa95** [comment]
Also, it seems like you have not pulled main into your branch. Not sure why it's not saying there's a merge conflict, but you should pull main (there's a couple changes that have been merged into main that are not showing up on your branch)

**Comment by mnunezsa95** [comment]
> Also, it seems like you have not pulled main into your branch. Not sure why it's not saying there's a merge conflict, but you should pull main (there's a couple changes that have been merged into main that are not showing up on your branch)

This was fixed by trevor

**Comment by SamPage4427** [comment]
> I think it looks good overall, but here's an issue I see. Not sure if it is out the scope of your ticket. Sam or Francis might be able to speak more on it. Right now, when a movie has alot of keywords, it starts to look very messy. Not sure if this is by design or accidental, but there's a way where you could make it so that only limit it to 3 or 5 keywords show up (again not sure if this is something in your scope or something that should even be done).
Yeah this should be handled in this ticket. There should only be like 5 keywords displayed but I'm not sure if it should be the top 5 or just a random 5.

**Comment by fostert14** [comment]
> > I think it looks good overall, but here's an issue I see. Not sure if it is out the scope of your ticket. Sam or Francis might be able to speak more on it. Right now, when a movie has alot of keywords, it starts to look very messy. Not sure if this is by design or accidental, but there's a way where you could make it so that only limit it to 3 or 5 keywords show up (again not sure if this is something in your scope or something that should even be done).
> 
> Yeah this should be handled in this ticket. There should only be like 5 keywords displayed but I'm not sure if it should be the top 5 or just a random 5.

**Comment by fostert14** [comment]
Accidentally closed pull request.

**Comment by SamPage4427** [comment]
image
Year and time should be a grey color. Also on larger sizes it doesn't say minutes after the time so it just looks like a random number

**Comment by fostert14** [comment]
> > I think it looks good overall, but here's an issue I see. Not sure if it is out the scope of your ticket. Sam or Francis might be able to speak more on it. Right now, when a movie has alot of keywords, it starts to look very messy. Not sure if this is by design or accidental, but there's a way where you could make it so that only limit it to 3 or 5 keywords show up (again not sure if this is something in your scope or something that should even be done).
> 
> Yeah this should be handled in this ticket. There should only be like 5 keywords displayed but I'm not sure if it should be the top 5 or just a random 5.

I changed it to just display the "top" keywords. Really whatever the first 5 keywords that are listed. If it needs to be random I can make further changes.

**Comment by fostert14** [comment]
> image Year and time should be a grey color. Also on larger sizes it doesn't say minutes after the time so it just looks like a random number image

Fixed.

**Review by SamPage4427 — APPROVED** [review]
Everything looks good. 
- Longer photos are maxed at 80% of the page height
- The keywords are displayed on the upper left for larger photos and below smaller ones and only display 5 keywords
- Movie title, date and minutes are in correct places
- date and minutes are the correct color as shown in the figma 
- missing minutes text has been fixed

Ticket is complete. Good work

**Review by jahorwitz — APPROVED** [review]

**Pull request merged**
