### PR TITLE
Fix/slop 27/improvement modal responsiveness

### PR DESCRIPTION
**Pull request by mnunezsa95**
## Describe your changes
**Due to the absence of a Figma template tailored for mobile design, I had to rely on my own judgment to make adjustments. In the second screenshot (after the changes), the elements may appear larger than in the original. This difference is due to the varying screen sizes of the devices used to capture the screenshots; the actual size of the elements remains unchanged.**

- Incorporating Slop-19 Client Context into the main branch resulted in two errors. Firstly, the SubmitList.jsx file was still utilizing the outdated CurrentUserContext. Secondly, the line "export * from "./hook/useCurrentUser"" in the index.js file within the graphQL folder needed to be removed for the webpage to load properly.
- Signup Modal: Although the signup modal didn't encounter responsiveness issues, I observed a discrepancy in the background color. Therefore, I made adjustments to ensure it aligns with the design in Figma.
- Login Modal: The Login Modal exhibited non-responsiveness below 442px, as the form components failed to adjust accordingly. This ticket addresses this issue by rearranging the nesting of the submit button and eliminating hardcoded widths. Additionally, I reordered the Remember Me and Forgot Password elements below the specified breakpoint in tailwind.config.js.

Before: the changes:
Screenshot 2024-03-05 at 6 01 01 PM

After the changes:
Screenshot 2024-03-05 at 5 54 45 PM

## Issue ticket number and link
[Slop-27](https://tripleten-apiary.atlassian.net/jira/software/projects/SLOP/boards/2?selectedIssue=SLOP-27)

## Checklist before requesting a review

- [X] I have performed a self-review of my code
- [ ] If there are changes to components, I have added / updated automated tests
- [ ] I have made any necessary updates to Storybook to accompany these changes
- [X] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings

### CODE REVIEW

**Comment by SamPage4427** [comment]
image
I would add more of a padding to the sides of the form inputs and the button. The modal close button should also change to be closer to the edge instead of almost overlapping the modal title.

**Comment by mnunezsa95** [comment]
> image I would add more of a padding to the sides of the form inputs and the button. The modal close button should also change to be closer to the edge instead of almost overlapping the modal title. Maybe on mobile screen sizes below 450px it should touch the sides and bottom?

This has been fixed. As for the suggestion about the modal, touching the sides and bottom, it looked a bit weird so I tried it out touching the top and sides. Let me know your thoughts on this.

**Comment by SamPage4427** [comment]
Looks good. I'm thinking maybe just keep it in the center. It doesn't look quite right on the top of the page and I don't think it would look right on the bottom either.

**Comment by mnunezsa95** [comment]
> Looks good. I'm thinking maybe just keep it in the center. It doesn't look quite right on the top of the page and I don't think it would look right on the bottom either.

Cool! I have re-centered back on xs-screen sizes

**Comment by SamPage4427** [comment]
The login, signup and add slops look correct, however, the slop fest modal and the preview modal still don't look correct.
image
The slop fest modal could just be a page responsiveness issue. I believe that Dexin is fixing the profile responsiveness that so that one should be fixed once he's done but the preview modal should be fixed.

**Comment by mnunezsa95** [comment]
> The slop fest modal could just be a page responsiveness issue. I believe that Dexin is fixing the profile responsiveness that so that one should be fixed once he's done but the preview modal should be fixed.

Ahh missed the part of the ticket that extends it to all modals. Let me take a look at all other modals (Add Slop fest, delete confirmation, preview modal). Will work on it later today.

**Comment by mnunezsa95** [comment]
> > The slop fest modal could just be a page responsiveness issue. I believe that Dexin is fixing the profile responsiveness that so that one should be fixed once he's done but the preview modal should be fixed.
> 
> Ahh missed the part of the ticket that extends it to all modals. Let me take a look at all other modals (Add Slop fest, delete confirmation, preview modal). Will work on it later today.

Here is the look at 320px-500px (xs screensize)

Screenshot 2024-03-08 at 3 04 15 PM

**Review by SamPage4427 — APPROVED** [review]
Everything looks good. Ticket complete

**Review by jahorwitz — APPROVED** [review]

**Pull request merged**
