### PR TITLE
Fix/slop-70 User Viewing a Fest Created by a now-deleted User

### PR DESCRIPTION
**Pull request by fdlai**
## Describe your changes
A very short fix so that an invitee to a fest, can now view a fest that was created by a deleted user.

## Issue ticket number and link
slop-70
https://tripleten-apiary.atlassian.net/jira/software/projects/SLOP/boards/2?selectedIssue=SLOP-70

## Checklist before requesting a review

- [x] I have performed a self-review of my code
- [ ] If there are changes to components, I have added / updated automated tests
- [ ] I have made any necessary updates to Storybook to accompany these changes
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

### CODE REVIEW

**Review by marzahlde09 — APPROVED** [review]
Elegant solution, works as described!

**Review by dani9401 — APPROVED** [review]
Looks good, Fred!

**Review by tomershvueli — APPROVED** [review]
Nice!

**Comment by tomershvueli** [comment]
@fdlai this branch is out of sync with `main` and has a merge conflict. Please resolve the conflict and tag me when it's up to date and I can merge it.

**Comment by fdlai** [comment]
> @fdlai this branch is out of sync with `main` and has a merge conflict. Please resolve the conflict and tag me when it's up to date and I can merge it.

@tomershvueli Hi! I think this branch is completely unnecessary now. I just checked and the branch that is conflicting with this one, has already fixed this issue. So, I think we can just delete this PR.

**Comment by tomershvueli** [comment]
> the branch that is conflicting with this one, has already fixed this issue

@fdlai Which branch is that?

**Comment by fdlai** [comment]
> > the branch that is conflicting with this one, has already fixed this issue
> 
> @fdlai Which branch is that?

It's this one: https://github.com/jahorwitz/slopopedia/commit/49c5210f15ad1d951791d9f77c0aa5d08046759b
It's already been merged into main.

**Comment by tomershvueli** [comment]
> It's already been merged into main.

D'oh! Thanks, confirmed.

**Pull request closed without merging**
