### PR TITLE
fix/slop-58/positioning of movie tags/keywords

### PR DESCRIPTION
**Pull request by dani9401**
## Describe your changes
I updated the style of the div responsible for setting the relative position necessary for the absolutely positioned keywords to use for correct placement. Screenshot attached to show what my local homepage looks like after this change. 

image

## Issue ticket number and link
https://tripleten-apiary.atlassian.net/jira/software/projects/SLOP/boards/2?selectedIssue=SLOP-58

## Checklist before requesting a review

- [x] I have performed a self-review of my code
- [ ] If there are changes to components, I have added / updated automated tests
- [ ] I have made any necessary updates to Storybook to accompany these changes
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings

### CODE REVIEW

**Comment by skovakina** [comment]
Seems good to me!

**Comment by dani9401** [comment]
> Seems good to me!

Thank you for checking this out! Would you be able to mark your review as "approved" when you get a free sec?

**Review by skovakina — COMMENTED** [review]
seems good to me

**Review by skovakina — APPROVED** [review]

**Review by fdlai — COMMENTED** [review]
Hi! I actually am not sure if this is how it's supposed to look or not? It looks off to me, because the tags potentially cover things that I imagine they shouldn't, such as the title of the movie. But maybe this is fine for now, and that should be a separate task to handle that. I'm not sure. @tomershvueli Can you chime in on this?

**Review by fdlai — APPROVED** [review]
Update: Tomer said we can handle other issues with it down the road.

**Comment by dani9401** [comment]
Thanks for the reviews! Moved to final code review now.

**Review by tomershvueli — APPROVED** [review]
👌

**Pull request merged**
