### PR TITLE
Fix / Slop-65 / Submit slop form validation

### PR DESCRIPTION
**Pull request by ATribbey**
## Describe your changes
Edit both releaseYear and runtime slop submission inputs to only accept 4 and 3 digits respectively. 

In the case of making these required fields, as the story seems to suggest, when reviewing the design spec on figma, Release Year and Runtime do not seem to be required fields. For that reason I left them as not required, but I can easily change this if need be, just let me know one way or another. 

## Issue ticket number and link
Slop-65
https://tripleten-apiary.atlassian.net/browse/SLOP-65?atlOrigin=eyJpIjoiNWJmNDYwZjRjZmEzNDUwMjhkZWIyNmI2ZjYyYTdiNGEiLCJwIjoiaiJ9

## Checklist before requesting a review

- [x] I have performed a self-review of my code
- [ ] If there are changes to components, I have added / updated automated tests
- [ ] I have made any necessary updates to Storybook to accompany these changes
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

### CODE REVIEW

**Review by fdlai — APPROVED** [review]
Seems to work great! 
One improvement might be to give the 'runtime' input a validation message as well. You can see in the screenshot that 'release year' has one, but 'runtime' doesn't.


Nice work!

**Comment by fdlai** [comment]
I pulled your changes. The update looks great!

**Review by dani9401 — APPROVED** [review]
This looks great for me. The validation works as expected, the error messages are helpful. Nice job!

**Review by tomershvueli — APPROVED** [review]
This is working great!

**Pull request merged**
